# Generated by Django 3.0.2 on 2020-02-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_remove_batch_rations_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='rations_sold',
            field=models.FloatField(default=0),
        ),
    ]
